client:
  logging:
    level: info
    format-type: line # allowed: line, structured (currently unused)
    output: stdout # allowed: stdout, stderr, filesystem
    colored: true
    report-caller: true
grpc:
  host: localhost
  port: 5099
logging:
  level: debug
  format-type: line # allowed: line, structured (currently unused)
  output: stdout # allowed: stdout, stderr, filesystem
  colored: false
  report-caller: false
messaging-server:
  host: localhost
  port: 4222
